### ISSUE TITLE
Readiness probe failed: HTTP probe failed with statuscode: 403

### ISSUE THREAD

**Issue by HBO2** [appscode/voyager#1296]
please have look at :
https://github.com/appscode/voyager/pull/1263

I created a comment about: Readiness probe failed: HTTP probe failed with statuscode: 403 in operator kubedb and voyager

**Comment by richerlariviere** [comment]
I noticed the same issue when I upgraded my K8s AKS cluster to 1.11.5 today (was working fine in 1.10.3).

**Comment by richerlariviere** [comment]
@HBO2 I don’t know if it’s something clean but it do the job for now at least. I didn’t have time to investigate much on this issue.

**Comment by tamalsaha** [comment]
@HBO2 , which version of Voyager are you using?

**Comment by gurrish** [comment]
> @HBO2 , which version of Voyager are you using? If you can share the operator log, that would help.

I'm using AKS, K8S 1.11.5, same problem if I use 7.4.0 or 8.0.1. Same problem if I install with helm and the quick install script.

**Comment by richerlariviere** [comment]
I got more information for you @tamalsaha. I put the Voyager logs but honestly they don't show anything interesting.

Voyager logs: [voyager.log](https://github.com/appscode/voyager/files/2668452/voyager.log)

Reproduction steps for Azure AKS:
```
az group create --name repro-aks --location eastus
az aks create --resource-group repro-aks --name repro-aks --kubernetes-version 1.11.5 --node-count 1
az aks get-credentials --resource-group repro-aks --name repro-aks
curl -fsSL https://raw.githubusercontent.com/appscode/voyager/8.0.1/hack/deploy/voyager.sh | bash -s -- --provider=azure
kubectl describe pods --namespace kube-system -l app=voyager
```
You'll see this output when you describe the pod:
```
Events:
  Type     Reason     Age                  From                               Message
  ----     ------     ----                 ----                               -------
  Normal   Scheduled  11m                  default-scheduler                  Successfully assigned kube-system/voyager-operator-77565ff47d-fqfjc to aks-nodepool1-34747613-0
  Normal   Pulling    11m                  kubelet, aks-nodepool1-34747613-0  pulling image "appscode/voyager:8.0.1"
  Normal   Pulled     11m                  kubelet, aks-nodepool1-34747613-0  Successfully pulled image "appscode/voyager:8.0.1"
  Normal   Created    11m                  kubelet, aks-nodepool1-34747613-0  Created container
  Normal   Started    11m                  kubelet, aks-nodepool1-34747613-0  Started container
  Warning  Unhealthy  11m                  kubelet, aks-nodepool1-34747613-0  Readiness probe failed: Get https://10.244.0.8:8443/healthz: net/http: request canceled while waiting forconnection (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  107s (x59 over 11m)  kubelet, aks-nodepool1-34747613-0  Readiness probe failed: HTTP probe failed with statuscode: 403
```

**Comment by gurrish** [comment]
In my live, staging and test AKS deployments, voyager operator started to print these logs

`I1212 11:55:05.663565       1 wrap.go:42] GET /healthz: (194.9µs) 403 [[kube-probe/1.11] 10.0.0.20:42834]
I1212 11:55:15.666062       1 wrap.go:42] GET /healthz: (2.2155ms) 403 [[kube-probe/1.11] 10.0.0.20:42906]
I1212 11:55:25.663711       1 wrap.go:42] GET /healthz: (189.5µs) 403 [[kube-probe/1.11] 10.0.0.20:42972]
I1212 11:55:35.673657       1 wrap.go:42] GET /healthz: (9.983202ms) 403 [[kube-probe/1.11] 10.0.0.20:43028]
I1212 11:55:45.663447       1 wrap.go:42] GET /healthz: (191.1µs) 403 [[kube-probe/1.11] 10.0.0.20:43086]
I1212 11:55:55.673657       1 wrap.go:42] GET /healthz: (9.928202ms) 403 [[kube-probe/1.11] 10.0.0.20:43160]
I1212 11:56:05.663779       1 wrap.go:42] GET /healthz: (193.3µs) 403 [[kube-probe/1.11] 10.0.0.20:43216]
I1212 11:56:15.671310       1 wrap.go:42] GET /healthz: (7.716102ms) 403 [[kube-probe/1.11] 10.0.0.20:43272]
I1212 11:56:25.663631       1 wrap.go:42] GET /healthz: (202.9µs) 403 [[kube-probe/1.11] 10.0.0.20:43338]
I1212 11:56:35.672705       1 wrap.go:42] GET /healthz: (9.192601ms) 403 [[kube-probe/1.11] 10.0.0.20:43410]
I1212 11:56:45.663830       1 wrap.go:42] GET /healthz: (203.4µs) 403 [[kube-probe/1.11] 10.0.0.20:43468]
I1212 11:56:55.673094       1 wrap.go:42] GET /healthz: (9.394ms) 403 [[kube-probe/1.11] 10.0.0.20:43524]
I1212 11:57:05.663687       1 wrap.go:42] GET /healthz: (202.5µs) 403 [[kube-probe/1.11] 10.0.0.20:43582]
I1212 11:57:15.695422       1 wrap.go:42] GET /healthz: (31.624002ms) 403 [[kube-probe/1.11] 10.0.0.20:43644]
I1212 11:57:25.663463       1 wrap.go:42] GET /healthz: (140.3µs) 403 [[kube-probe/1.11] 10.0.0.20:43720]
I1212 11:57:35.679785       1 wrap.go:42] GET /healthz: (16.144602ms) 403 [[kube-probe/1.11] 10.0.0.20:43776]
I1212 11:57:45.663773       1 wrap.go:42] GET /healthz: (173.9µs) 403 [[kube-probe/1.11] 10.0.0.20:43834]
I1212 11:57:55.672784       1 wrap.go:42] GET /healthz: (8.799301ms) 403 [[kube-probe/1.11] 10.0.0.20:43890]
I1212 11:58:05.663529       1 wrap.go:42] GET /healthz: (150.7µs) 403 [[kube-probe/1.11] 10.0.0.20:43948]
I1212 11:58:15.669146       1 wrap.go:42] GET /healthz: (5.6044ms) 403 [[kube-probe/1.11] 10.0.0.20:44020]
I1212 11:58:25.663606       1 wrap.go:42] GET /healthz: (196.3µs) 403 [[kube-probe/1.11] 10.0.0.20:44086]
I1212 11:58:35.666372       1 wrap.go:42] GET /healthz: (2.555401ms) 403 [[kube-probe/1.11] 10.0.0.20:44142]
I1212 11:58:45.663882       1 wrap.go:42] GET /healthz: (271.4µs) 403 [[kube-probe/1.11] 10.0.0.20:44198]
I1212 11:58:55.665845       1 wrap.go:42] GET /healthz: (2.142201ms) 403 [[kube-probe/1.11] 10.0.0.20:44264]
I1212 11:59:05.663940       1 wrap.go:42] GET /healthz: (222.9µs) 403 [[kube-probe/1.11] 10.0.0.20:44330]
I1212 11:59:15.672537       1 wrap.go:42] GET /healthz: (8.697401ms) 403 [[kube-probe/1.11] 10.0.0.20:44386]
I1212 11:59:25.663569       1 wrap.go:42] GET /healthz: (178.6µs) 403 [[kube-probe/1.11] 10.0.0.20:44452]
I1212 11:59:35.665640       1 wrap.go:42] GET /healthz: (2ms) 403 [[kube-probe/1.11] 10.0.0.20:44508]
I1212 11:59:45.663562       1 wrap.go:42] GET /healthz: (171.5µs) 403 [[kube-probe/1.11] 10.0.0.20:44580]
I1212 11:59:55.691390       1 wrap.go:42] GET /healthz: (27.398404ms) 403 [[kube-probe/1.11] 10.0.0.20:44638]`

And I can not create or modify any ingresses anymore 
`kubectl apply -f ingress.yml

Error from server (InternalError): error when creating "ingress.yml": Internal error occurred: failed calling admission webhook "admission.voyager.appscode.com": the server is currently unable to handle the request`

so I'm pretty much in deep shit right now since I cannot modify or create an ingress in any of my environments.

the existing ingresses still work as they should.

**Comment by diptadas** [comment]
Hi, we have tested Voyager 8.0.1 with AKS (k8s version 1.11.5) but didn't face any such issues. It might be caused by https://github.com/Azure/AKS/issues/417. 

However, we have added an option to disable readiness and liveliness probes in chart installation (#1309). You can now set `apiserver.healthcheck.enabled` to `false` to disable readiness and liveliness probes.

**Comment by tamalsaha** [comment]
Folks, this readiness probe failure issue has a workaround. You can see it here: https://github.com/helm/charts/issues/10222#issuecomment-450924832

Thanks Derek Martin for pointing out the fix.
