### ISSUE TITLE
Bug: annotations are not applied

### ISSUE THREAD

**Issue by julianvmodesto** [appscode/voyager#266]
Looks like there's a regression in 3.0.0 and none of the below annotations apply.

```
    ingress.appscode.com/annotations-service: |
        {
            "service.beta.kubernetes.io/aws-load-balancer-backend-protocol": "http",
            "service.beta.kubernetes.io/aws-load-balancer-proxy-protocol": "*",
            "service.beta.kubernetes.io/aws-load-balancer-ssl-cert": "arn:aws:acm:..."
        }
```

```
    ingress.appscode.com/annotations-service: '{"service.beta.kubernetes.io/aws-load-balancer-ssl-cert": "arn:aws:acm:..."`}'
```

```
    ingress.voyager.appscode.com/annotations-service: |
        {
            "service.beta.kubernetes.io/aws-load-balancer-backend-protocol": "http",
            "service.beta.kubernetes.io/aws-load-balancer-proxy-protocol": "*",
            "service.beta.kubernetes.io/aws-load-balancer-ssl-cert": "arn:aws:acm:..."
        }
```

```
    ingress.voyager.appscode.com/annotations-service: '{"service.beta.kubernetes.io/aws-load-balancer-ssl-cert": "arn:aws:acm:..."`}'
```

**Comment by julianvmodesto** [comment]
Oops sorry, I'm getting interesting behavior... Confirming first.

**Comment by julianvmodesto** [comment]
Looks like only the multi-line annotation doesn't get picked up.

```
    ingress.appscode.com/annotations-service: |
        {
            "service.beta.kubernetes.io/aws-load-balancer-backend-protocol": "http",
            "service.beta.kubernetes.io/aws-load-balancer-proxy-protocol": "*",
            "service.beta.kubernetes.io/aws-load-balancer-ssl-cert": "arn:aws:acm:..."
        }
```

**Comment by julianvmodesto** [comment]
Also -- the behavior is flaky when updating this annotation multiple times.

**Comment by tamalsaha** [comment]
@sadlil , can you add  a test for the multi-line annotations?

**Comment by sadlil** [comment]
@tamalsaha i have manually tested this issue against current master branch. This issue is not occurring. I have tried updating the annotations multiple times, targeted updates happens as expected. But we need to stay sharp to maintain both `yaml` multi-line format and `json` format. Any invalid json can update the ingress but it will not update the target service or pod.
And single line json map must be within `'{}'` (single quotes)

@julianvmodesto I am closing the issue. Feel free to reopen if our upcoming release doesn't work for you.
