### ISSUE TITLE
Support direct scrapping via Prometheus

### ISSUE THREAD

**Issue by jalberto** [appscode/voyager#593]
helm chart stable/prometheus support annotations for configuration, so I will like to add annotations to operator like this:

    prometheus.io/scrape: "true"

**Comment by tamalsaha** [comment]
https://github.com/prometheus/prometheus/blob/6bfc8f094ceb817c3563d51e7181a4a663a4b384/documentation/examples/prometheus-kubernetes.yml#L131

**Comment by tamalsaha** [comment]
I have looked into this. There are 2 ways to get Prometheus ready metrics in Voyager. We expose this using https://github.com/appscode/haproxy_exporter .

- side-car-exporter for HAProxy pods: Currently voyager can automatically create ServiceMonitor objects for prometheus-operator. https://github.com/appscode/voyager/blob/master/docs/user-guide/ingress/stats-and-prometheus.md#using-prometheus . In this mode, a side-car container is run with HAProxy pods.

- out-of-pod exporter: Voyager operator itselff can expose metrics for all HAProxy pods it manages using its own built-in exporter service. This is exposed via port 56790 port. This can't be used by prometheus-operator due to  https://github.com/coreos/prometheus-operator/issues/387 . But if someone if configuring prometheus directly, this could used to scrape HAProxy metrics. The limitation of this approach is that, `prometheus.io/scrape: "true"` annotations can't be applied to the operator service pod, if you have more than one Ingress to manager.

To allow direct scraping of HAProxy stats, 2 options are available:
- opt 1: we only create the stats service for each HAProxy, then apply the annotations like `prometheus.io/scrape: "true"` but use the exporter built-in voyager exporter. This can be generalized by supporting `ingress.appscode.com/annotations-stats: {"k": "v"}` annotation that allows use to apply any annotation to the Stats service for HAproxy pods. Potential issues:
  - if there are many HAProxy pods, and only one operator pod, I wonder if that becomes a bottle neck. I don't this to be a major issue.
 
- opt 2: In this mode, we create the stats service and add side-car but instead of creating a ServiceMonitor, we apply the `prometheus.io/scrape: "true"` annotations on stats service to scrape annotations from side-car. This can be enabled by annotation like `ingress.appscode.com/monitoring-agent: prometheus-direct` or something.

My question what makes sense, folks?

cc: @julianvmodesto

**Comment by jalberto** [comment]
Great analysis!

IMHO I prefer the approach that creates less objects (so less moving parts). Anyway if exporter is enabled is because we want to use prometheus, so prometheus annotations can be auto-applied.

**Comment by julianvmodesto** [comment]
I'm happy with the existing behavior with a sidecar HAProxy exporters and the ServiceMonitor since we run several voyager pods, with about one voyager pod per Node in our cluster.

**Comment by tamalsaha** [comment]
#703 adds supports a new value for annotation 
`ingress.appscode.com/monitoring-agent: prometheus-builtin`

If this annotation is used, the stats-server will be annotated with `prometheus.io/` annotations

```
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  namespace: demo
  annotations:
    ingress.appscode.com/stats: 'true'
    ingress.appscode.com/monitoring-agent: 'prometheus-builtin'
spec:
  backend:
    serviceName: test-server
    servicePort: 80
  rules:
  - host: voyager.demo
    http:
      paths:
      - backend:
          serviceName: test-server
          servicePort: 80



$ kubectl get svc -n demo voyager-test-ingress-stats -o yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    ingress.appscode.com/origin-api-schema: voyager.appscode.com/v1beta1
    ingress.appscode.com/origin-name: test-ingress
    prometheus.io/path: /voyager.appscode.com/v1beta1/namespaces/demo/ingresses/test-ingress/metrics
    prometheus.io/port: "56790"
    prometheus.io/scrape: "true"
  creationTimestamp: 2017-11-14T23:38:32Z
  labels:
    feature: stats
    origin: voyager
    origin-api-group: voyager.appscode.com
    origin-name: test-ingress
  name: voyager-test-ingress-stats
  namespace: demo
  resourceVersion: "3189"
  selfLink: /api/v1/namespaces/demo/services/voyager-test-ingress-stats
  uid: ed165966-c994-11e7-871d-080027676468
spec:
  clusterIP: 10.0.0.11
  ports:
  - name: stats
    port: 56789
    protocol: TCP
    targetPort: stats
  - name: http
    port: 56790
    protocol: TCP
    targetPort: http
  selector:
    origin: voyager
    origin-api-group: voyager.appscode.com
    origin-name: test-ingress
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

**Comment by jalberto** [comment]
this sounds great! will try it soon as possible

**Comment by tamalsaha** [comment]
@jalberto , I will ping you when we cut the next rc with this feature.

**Comment by tamalsaha** [comment]
@the-redback , we need to copy something similar to https://github.com/kubedb/cli/blob/91789463b67019b71bcf9796ec6c4e7a6bc5ad41/docs/guides/mongodb/monitoring/using-builtin-prometheus.md

**Comment by tamalsaha** [comment]
Done.

**Comment by tamalsaha** [comment]
This is documented here: https://github.com/appscode/voyager/blob/master/docs/guides/ingress/monitoring/using-builtin-prometheus.md
