### ISSUE TITLE
Allow dynamic configuration based on annotations/labels (feature request)

### ISSUE THREAD

**Issue by jalberto** [appscode/voyager#600]
In CI/CD cases is common to create several deploys using git user or branch name for demo/testing proposes. To avoid interact directly with voyager, any service can use annotations for basic voyager configuration, so a foo-staging-svc can use:

```
ingress.appscode.com/ingress-name: foo
ingress.appscode.com/ingress-opts: {mode: http, port: 80, host: staging.foo.com}
```

A similar approach is used by traefik in docker swarm mode.

**Comment by tamalsaha** [comment]
ref: https://docs.traefik.io/user-guide/swarm-mode/#deploy-your-apps

**Comment by munnerz** [comment]
I'm not sure about something like this. It seems to open up the potential for privilege escalation, and would allow a user to create an ingress despite only having authorization to create a service.

In your CI/CD pipeline, why could you not create an Ingress resource alongside your Service? The whole point of an Ingress is to decouple applications from interacting with the ingress controller - so I don't understand `To avoid interact directly with voyager` - perhaps I am just not familiar with how voyager operates 😄

**Comment by tamalsaha** [comment]
Hey @munnerz , great to see you here!

I agree with your point about privilege escalation. But the issue here is that Voyager creates a separate LB (haproxy pods) for each Ingress object. This can be problematic if you have a lot of services. ref: https://github.com/kubernetes/ingress-nginx/issues/1539

Currently users have to update the Ingress YAML to expose additional services from an Ingress.

**Comment by tamalsaha** [comment]
Dup #637
