### ISSUE TITLE
Deployment model of voyager a bit overcomplex?

### ISSUE THREAD

**Issue by sokoow** [appscode/voyager#924]
Hey, this is not a criticism but an observation :) You've a great product, with great features and potential, but deployment model is a bit of an uphill trip. One example:

```
checking whether extended apiserver feature is enabled
missing key requestheader-client-ca-file
Set --requestheader-client-ca-file flag on Kubernetes apiserver
```

Well, this is going to put off majority of customers that already have kubes running in prod -  I can't imagine somebody stopping and changing all their masters settings :/ Why do you need this to be enabled ?

I love your product, but let's get back to reality, I remember how easy it was to deploy it couple of releases ago - can this be brought back please? Greetings :)

**Comment by tamalsaha** [comment]
@sokoow , I am going to say sorry upfront because my answer is probably going to disappoint you.

In 6.0.0-rc.x release, we are using the [ValidationWebhook](https://kubernetes.io/docs/admin/admission-controllers/#validatingadmissionwebhook-alpha-in-18-beta-in-19) feature to ensure that users get early warning when there is an error in Ingress yaml. This helps with lot of support requests we get. But this comes with the additional complexity of installing a Kubernetes extended api service.

This aggregate apiserver feature is in beta since Kubernetes 1.8. This is default on since Kube 1.9. This is going GA with next release of Kubernetes this month. http://blog.kubernetes.io/2018/03/first-beta-version-of-kubernetes-1-10.html . So, while this is an issue for some users at the moment, I am hoping that over the next 3 months this should be enabled for most common installation mechanism of Kubernetes. Once installed, this stays invisible until user provides a bad ingress yaml. This does not increase the complexity of using Voyager post installation.

I have also done some cleanup of the installation page. https://github.com/appscode/voyager/blob/master/docs/setup/install.md . So, the script installation is a single command if you just go with all the default options.

**Comment by sokoow** [comment]
See, I knew that there's a good and valid reason for it :) Thanks for commenting, now it looks like we need to upgrade to 1.9, whew :D
